/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.Controlador;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author fp
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        
        // Titulo de la ventana
        setTitle("Aprende nuestro mapa");
              
        // Ponemos una imagen desde el inicio
        // Creamos una imagen
        ImageIcon imagen = new ImageIcon("img/mapaEsp.jpg");
        // Actualizamos la imagen
        imagen = new ImageIcon(imagen.getImage().getScaledInstance(320, 170, Image.SCALE_DEFAULT));
        // Colocamos la imagen en la etiqueta
        lblImgInicio.setIcon(imagen);
        
        // Localizacion en el centro
        setLocationRelativeTo(null);
        
        // Nuevo controlador
        Controlador.iniciarPrograma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPreguntasProvincias = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        lblEnunciado1 = new javax.swing.JLabel();
        lblImgInicio1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNumeroRandomProvincias = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRespuestaProvincias = new javax.swing.JTextField();
        btnResponderProvincias = new javax.swing.JButton();
        menuBar1 = new javax.swing.JMenuBar();
        menuInformacion1 = new javax.swing.JMenu();
        itemInfoProvincia1 = new javax.swing.JMenuItem();
        menuAyuda1 = new javax.swing.JMenu();
        menuInfo1 = new javax.swing.JMenuItem();
        menuSobreMi1 = new javax.swing.JMenuItem();
        dialogPreguntasComunidades = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        lblEnunciado2 = new javax.swing.JLabel();
        lblImgInicio2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblNumeroRandomComunidad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtResponderComunidad = new javax.swing.JTextField();
        btnRespuesta2 = new javax.swing.JButton();
        menuBar2 = new javax.swing.JMenuBar();
        menuInformacion2 = new javax.swing.JMenu();
        itemInfoProvincia2 = new javax.swing.JMenuItem();
        menuAyuda2 = new javax.swing.JMenu();
        menuInfo2 = new javax.swing.JMenuItem();
        menuSobreMi2 = new javax.swing.JMenuItem();
        dialogPreguntasCapitalProvincias = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        lblEnunciado3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCapitalesProvincias = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRespuestaCapitalesProvincias = new javax.swing.JTextField();
        btnResponderCapitalesProvincias = new javax.swing.JButton();
        menuBar3 = new javax.swing.JMenuBar();
        menuInformacion3 = new javax.swing.JMenu();
        itemInfoProvincia3 = new javax.swing.JMenuItem();
        menuAyuda3 = new javax.swing.JMenu();
        menuInfo3 = new javax.swing.JMenuItem();
        menuSobreMi3 = new javax.swing.JMenuItem();
        dialogPreguntasProvinciasCapital = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        lblEnunciado5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblNombreCapital = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRespuestaProvinciasCapitales = new javax.swing.JTextField();
        btnResponderProvinciasCapitales = new javax.swing.JButton();
        menuBar4 = new javax.swing.JMenuBar();
        menuInformacion4 = new javax.swing.JMenu();
        itemInfoProvincia4 = new javax.swing.JMenuItem();
        menuAyuda4 = new javax.swing.JMenu();
        menuInfo4 = new javax.swing.JMenuItem();
        menuSobreMi4 = new javax.swing.JMenuItem();
        dialogInforProvincias = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        lblEnunciado4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        btnVerProvincia = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblInfoProvincia = new javax.swing.JLabel();
        lblNombreProvincia = new javax.swing.JLabel();
        lblImg1Provincia = new javax.swing.JLabel();
        lblImg3Provincia = new javax.swing.JLabel();
        lblImg2Provincia = new javax.swing.JLabel();
        btnCerrarInfoProvincia = new javax.swing.JButton();
        dialogAyuda = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        lblEnunciado6 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCerrarAyuda = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblEnunciado = new javax.swing.JLabel();
        lblImgInicio = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        bntAleatoriasProvinciasTool = new javax.swing.JButton();
        bntAleatoriasComunidadTool = new javax.swing.JButton();
        btnCapitalProvinciaTool = new javax.swing.JButton();
        btnProvinciaCapitalTool = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAleatoriasProvincias = new javax.swing.JButton();
        btnAleatoriasComunidad = new javax.swing.JButton();
        btnCapitalProvincia = new javax.swing.JButton();
        btnProvinciaCapital = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuPreguntar = new javax.swing.JMenu();
        itemAleatoriasProvincias = new javax.swing.JMenuItem();
        itemAleatoriasComunidad = new javax.swing.JMenuItem();
        itemCapitalProvincia = new javax.swing.JMenuItem();
        itemProvinciaCaptial = new javax.swing.JMenuItem();
        menuInformacion = new javax.swing.JMenu();
        itemInfoProvincia = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenuItem();
        menuSobreMi = new javax.swing.JMenuItem();

        dialogPreguntasProvincias.setModal(true);

        jPanel3.setBackground(new java.awt.Color(129, 166, 241));
        jPanel3.setForeground(new java.awt.Color(129, 166, 241));

        lblEnunciado1.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        lblEnunciado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnunciado1.setText("Preguntando Provincias");
        lblEnunciado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Preguntas: "));
        jPanel4.setOpaque(false);

        jLabel1.setText("Dame la provicia numero: ");

        lblNumeroRandomProvincias.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        lblNumeroRandomProvincias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroRandomProvincias.setText("...");

        jLabel3.setText("Provincia: ");

        btnResponderProvincias.setText("Responder");
        btnResponderProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderProvinciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtRespuestaProvincias))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNumeroRandomProvincias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnResponderProvincias))
                        .addGap(0, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumeroRandomProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRespuestaProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnResponderProvincias)
                .addGap(0, 61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImgInicio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEnunciado1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblEnunciado1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImgInicio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        menuInformacion1.setText("Informacion");

        itemInfoProvincia1.setText("Informacion Provincias");
        itemInfoProvincia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInfoProvincia1ActionPerformed(evt);
            }
        });
        menuInformacion1.add(itemInfoProvincia1);

        menuBar1.add(menuInformacion1);

        menuAyuda1.setText("Ayuda");

        menuInfo1.setText("Ayuda");
        menuInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfo1ActionPerformed(evt);
            }
        });
        menuAyuda1.add(menuInfo1);

        menuSobreMi1.setText("Sobre mi...");
        menuSobreMi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreMi1ActionPerformed(evt);
            }
        });
        menuAyuda1.add(menuSobreMi1);

        menuBar1.add(menuAyuda1);

        dialogPreguntasProvincias.setJMenuBar(menuBar1);

        javax.swing.GroupLayout dialogPreguntasProvinciasLayout = new javax.swing.GroupLayout(dialogPreguntasProvincias.getContentPane());
        dialogPreguntasProvincias.getContentPane().setLayout(dialogPreguntasProvinciasLayout);
        dialogPreguntasProvinciasLayout.setHorizontalGroup(
            dialogPreguntasProvinciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogPreguntasProvinciasLayout.setVerticalGroup(
            dialogPreguntasProvinciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogPreguntasComunidades.setModal(true);

        jPanel5.setBackground(new java.awt.Color(129, 166, 241));
        jPanel5.setForeground(new java.awt.Color(129, 166, 241));

        lblEnunciado2.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        lblEnunciado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnunciado2.setText("Preguntando Comunidad");
        lblEnunciado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Preguntas: "));
        jPanel7.setOpaque(false);

        jLabel4.setText("Dame la Comunidad Autonoma numero: ");

        lblNumeroRandomComunidad.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        lblNumeroRandomComunidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroRandomComunidad.setText("...");

        jLabel6.setText("Comunidad: ");

        btnRespuesta2.setText("Respuesta");
        btnRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuesta2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResponderComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNumeroRandomComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4)
            .addComponent(btnRespuesta2)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumeroRandomComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtResponderComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRespuesta2)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEnunciado2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(lblImgInicio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblEnunciado2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImgInicio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        menuInformacion2.setText("Informacion");

        itemInfoProvincia2.setText("Informacion Provincias");
        itemInfoProvincia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInfoProvincia2ActionPerformed(evt);
            }
        });
        menuInformacion2.add(itemInfoProvincia2);

        menuBar2.add(menuInformacion2);

        menuAyuda2.setText("Ayuda");

        menuInfo2.setText("Ayuda");
        menuInfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfo2ActionPerformed(evt);
            }
        });
        menuAyuda2.add(menuInfo2);

        menuSobreMi2.setText("Sobre mi...");
        menuSobreMi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreMi2ActionPerformed(evt);
            }
        });
        menuAyuda2.add(menuSobreMi2);

        menuBar2.add(menuAyuda2);

        dialogPreguntasComunidades.setJMenuBar(menuBar2);

        javax.swing.GroupLayout dialogPreguntasComunidadesLayout = new javax.swing.GroupLayout(dialogPreguntasComunidades.getContentPane());
        dialogPreguntasComunidades.getContentPane().setLayout(dialogPreguntasComunidadesLayout);
        dialogPreguntasComunidadesLayout.setHorizontalGroup(
            dialogPreguntasComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogPreguntasComunidadesLayout.setVerticalGroup(
            dialogPreguntasComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogPreguntasCapitalProvincias.setModal(true);

        jPanel6.setBackground(new java.awt.Color(129, 166, 241));
        jPanel6.setForeground(new java.awt.Color(129, 166, 241));

        lblEnunciado3.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        lblEnunciado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnunciado3.setText("Preguntando Capitales de Provincias");
        lblEnunciado3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Preguntas: "));
        jPanel8.setOpaque(false);

        jLabel2.setText("Dame la Capital de esta Provincia: ");

        lblCapitalesProvincias.setFont(new java.awt.Font("sansserif", 3, 16)); // NOI18N
        lblCapitalesProvincias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCapitalesProvincias.setText("...");

        jLabel5.setText("Capital: ");

        btnResponderCapitalesProvincias.setText("Responder");
        btnResponderCapitalesProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderCapitalesProvinciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCapitalesProvincias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRespuestaCapitalesProvincias)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnResponderCapitalesProvincias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCapitalesProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRespuestaCapitalesProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnResponderCapitalesProvincias)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEnunciado3, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnunciado3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuInformacion3.setText("Informacion");

        itemInfoProvincia3.setText("Informacion Provincias");
        itemInfoProvincia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInfoProvincia3ActionPerformed(evt);
            }
        });
        menuInformacion3.add(itemInfoProvincia3);

        menuBar3.add(menuInformacion3);

        menuAyuda3.setText("Ayuda");

        menuInfo3.setText("Ayuda");
        menuInfo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfo3ActionPerformed(evt);
            }
        });
        menuAyuda3.add(menuInfo3);

        menuSobreMi3.setText("Sobre mi...");
        menuSobreMi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreMi3ActionPerformed(evt);
            }
        });
        menuAyuda3.add(menuSobreMi3);

        menuBar3.add(menuAyuda3);

        dialogPreguntasCapitalProvincias.setJMenuBar(menuBar3);

        javax.swing.GroupLayout dialogPreguntasCapitalProvinciasLayout = new javax.swing.GroupLayout(dialogPreguntasCapitalProvincias.getContentPane());
        dialogPreguntasCapitalProvincias.getContentPane().setLayout(dialogPreguntasCapitalProvinciasLayout);
        dialogPreguntasCapitalProvinciasLayout.setHorizontalGroup(
            dialogPreguntasCapitalProvinciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogPreguntasCapitalProvinciasLayout.setVerticalGroup(
            dialogPreguntasCapitalProvinciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogPreguntasProvinciasCapital.setModal(true);

        jPanel11.setBackground(new java.awt.Color(129, 166, 241));
        jPanel11.setForeground(new java.awt.Color(129, 166, 241));

        lblEnunciado5.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        lblEnunciado5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnunciado5.setText("Preguntando Provincias de Capitales");
        lblEnunciado5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Preguntas: "));
        jPanel12.setOpaque(false);

        jLabel9.setText("Dame la Provincia de esta Capital: ");

        lblNombreCapital.setFont(new java.awt.Font("sansserif", 3, 16)); // NOI18N
        lblNombreCapital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCapital.setText("...");

        jLabel10.setText("Provincia:");

        btnResponderProvinciasCapitales.setText("Responder");
        btnResponderProvinciasCapitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderProvinciasCapitalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCapital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRespuestaProvinciasCapitales)))
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnResponderProvinciasCapitales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRespuestaProvinciasCapitales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnResponderProvinciasCapitales)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEnunciado5, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnunciado5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuInformacion4.setText("Informacion");

        itemInfoProvincia4.setText("Informacion Provincias");
        itemInfoProvincia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInfoProvincia4ActionPerformed(evt);
            }
        });
        menuInformacion4.add(itemInfoProvincia4);

        menuBar4.add(menuInformacion4);

        menuAyuda4.setText("Ayuda");

        menuInfo4.setText("Ayuda");
        menuInfo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfo4ActionPerformed(evt);
            }
        });
        menuAyuda4.add(menuInfo4);

        menuSobreMi4.setText("Sobre mi...");
        menuSobreMi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreMi4ActionPerformed(evt);
            }
        });
        menuAyuda4.add(menuSobreMi4);

        menuBar4.add(menuAyuda4);

        dialogPreguntasProvinciasCapital.setJMenuBar(menuBar4);

        javax.swing.GroupLayout dialogPreguntasProvinciasCapitalLayout = new javax.swing.GroupLayout(dialogPreguntasProvinciasCapital.getContentPane());
        dialogPreguntasProvinciasCapital.getContentPane().setLayout(dialogPreguntasProvinciasCapitalLayout);
        dialogPreguntasProvinciasCapitalLayout.setHorizontalGroup(
            dialogPreguntasProvinciasCapitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogPreguntasProvinciasCapitalLayout.setVerticalGroup(
            dialogPreguntasProvinciasCapitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogInforProvincias.setModal(true);

        jPanel9.setBackground(new java.awt.Color(129, 166, 241));
        jPanel9.setForeground(new java.awt.Color(129, 166, 241));

        lblEnunciado4.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        lblEnunciado4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnunciado4.setText("Informacion de una Provincia");
        lblEnunciado4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincias"));
        jPanel10.setOpaque(false);

        jLabel8.setText("Provincia:");

        btnVerProvincia.setText("Ver Provincia");
        btnVerProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProvinciaActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre: ");

        jLabel11.setText("Informacion: ");

        jLabel12.setText("Imagenes: ");

        lblInfoProvincia.setText("...");

        lblNombreProvincia.setText("...");

        lblImg1Provincia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg1Provincia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImg3Provincia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg3Provincia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImg2Provincia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg2Provincia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCerrarInfoProvincia.setText("Cerrar");
        btnCerrarInfoProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarInfoProvinciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfoProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProvincia))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(lblNombreProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg1Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImg2Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImg3Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnVerProvincia))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnCerrarInfoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerProvincia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblNombreProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblInfoProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg1Provincia, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(lblImg2Provincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImg3Provincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnCerrarInfoProvincia)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnunciado4, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnunciado4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dialogInforProvinciasLayout = new javax.swing.GroupLayout(dialogInforProvincias.getContentPane());
        dialogInforProvincias.getContentPane().setLayout(dialogInforProvinciasLayout);
        dialogInforProvinciasLayout.setHorizontalGroup(
            dialogInforProvinciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogInforProvinciasLayout.setVerticalGroup(
            dialogInforProvinciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogAyuda.setModal(true);

        jPanel13.setBackground(new java.awt.Color(129, 166, 241));
        jPanel13.setForeground(new java.awt.Color(129, 166, 241));

        lblEnunciado6.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        lblEnunciado6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnunciado6.setText("Ayuda");
        lblEnunciado6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincias"));
        jPanel15.setOpaque(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("El programa trata: \n1. Preguntar aleatoriamente Provincias\n2. Preguntar aleatoriamente Comunidades\n3. Preguntar Capitales por las Provincias.\n4. Preguntar Provincias por las Capitales .\n5. Puedes mirar la informacion de las Provincias.\n\nCREADO POR RUBEN PALOMO YUSTE\nrubenpalomoyuste@gmail.com");
        jScrollPane1.setViewportView(jTextArea1);

        btnCerrarAyuda.setText("Cerrar");
        btnCerrarAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnCerrarAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrarAyuda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnunciado6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnunciado6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dialogAyudaLayout = new javax.swing.GroupLayout(dialogAyuda.getContentPane());
        dialogAyuda.getContentPane().setLayout(dialogAyudaLayout);
        dialogAyudaLayout.setHorizontalGroup(
            dialogAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogAyudaLayout.setVerticalGroup(
            dialogAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(129, 166, 241));
        jPanel1.setForeground(new java.awt.Color(129, 166, 241));

        lblEnunciado.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        lblEnunciado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnunciado.setText("Juega & Aprende");
        lblEnunciado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jToolBar1.setBackground(new java.awt.Color(74, 96, 255));
        jToolBar1.setForeground(new java.awt.Color(74, 96, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        bntAleatoriasProvinciasTool.setText("Provincias Aleatorias");
        bntAleatoriasProvinciasTool.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntAleatoriasProvinciasTool.setFocusable(false);
        bntAleatoriasProvinciasTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntAleatoriasProvinciasTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntAleatoriasProvinciasTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAleatoriasProvinciasToolActionPerformed(evt);
            }
        });
        jToolBar1.add(bntAleatoriasProvinciasTool);

        bntAleatoriasComunidadTool.setText("Comunidad Aleatorias");
        bntAleatoriasComunidadTool.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntAleatoriasComunidadTool.setFocusable(false);
        bntAleatoriasComunidadTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntAleatoriasComunidadTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntAleatoriasComunidadTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAleatoriasComunidadToolActionPerformed(evt);
            }
        });
        jToolBar1.add(bntAleatoriasComunidadTool);

        btnCapitalProvinciaTool.setText("Capital por Provincia");
        btnCapitalProvinciaTool.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCapitalProvinciaTool.setFocusable(false);
        btnCapitalProvinciaTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapitalProvinciaTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapitalProvinciaTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapitalProvinciaToolActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCapitalProvinciaTool);

        btnProvinciaCapitalTool.setText("Provincia por Capital");
        btnProvinciaCapitalTool.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProvinciaCapitalTool.setFocusable(false);
        btnProvinciaCapitalTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProvinciaCapitalTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProvinciaCapitalTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvinciaCapitalToolActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProvinciaCapitalTool);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Preguntas: "));
        jPanel2.setOpaque(false);

        btnAleatoriasProvincias.setText("Preguntar aleatorias Provincias");
        btnAleatoriasProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatoriasProvinciasActionPerformed(evt);
            }
        });

        btnAleatoriasComunidad.setText("Preguntar aleatorias Comunidad");
        btnAleatoriasComunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatoriasComunidadActionPerformed(evt);
            }
        });

        btnCapitalProvincia.setText("Preguntar Capital por Provincia");
        btnCapitalProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapitalProvinciaActionPerformed(evt);
            }
        });

        btnProvinciaCapital.setText("Preguntar Provincia por Capital");
        btnProvinciaCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvinciaCapitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAleatoriasProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAleatoriasComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapitalProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProvinciaCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAleatoriasProvincias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAleatoriasComunidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCapitalProvincia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProvinciaCapital)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImgInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        menuPreguntar.setText("Preguntar");

        itemAleatoriasProvincias.setText("Provincias Aleatorias");
        itemAleatoriasProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAleatoriasProvinciasActionPerformed(evt);
            }
        });
        menuPreguntar.add(itemAleatoriasProvincias);

        itemAleatoriasComunidad.setText("Comunidad Aleatorias");
        itemAleatoriasComunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAleatoriasComunidadActionPerformed(evt);
            }
        });
        menuPreguntar.add(itemAleatoriasComunidad);

        itemCapitalProvincia.setText("Capital por Provincia");
        itemCapitalProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCapitalProvinciaActionPerformed(evt);
            }
        });
        menuPreguntar.add(itemCapitalProvincia);

        itemProvinciaCaptial.setText("Provincia por Capital");
        itemProvinciaCaptial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProvinciaCaptialActionPerformed(evt);
            }
        });
        menuPreguntar.add(itemProvinciaCaptial);

        menuBar.add(menuPreguntar);

        menuInformacion.setText("Informacion");

        itemInfoProvincia.setText("Informacion Provincias");
        itemInfoProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInfoProvinciaActionPerformed(evt);
            }
        });
        menuInformacion.add(itemInfoProvincia);

        menuBar.add(menuInformacion);

        menuAyuda.setText("Ayuda");

        menuInfo.setText("Ayuda");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });
        menuAyuda.add(menuInfo);

        menuSobreMi.setText("Sobre mi...");
        menuSobreMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreMiActionPerformed(evt);
            }
        });
        menuAyuda.add(menuSobreMi);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAleatoriasComunidadToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAleatoriasComunidadToolActionPerformed
        // TODO add your handling code here:
        Controlador.randomComunidad(lblNumeroRandomComunidad);
        
        // Creamos una imagen
        ImageIcon imagen = new ImageIcon("img/mapaPuntos2.png");
        // Actualizamos la imagen
        imagen = new ImageIcon(imagen.getImage().getScaledInstance(350, 240, Image.SCALE_DEFAULT));
        // Colocamos la imagen en la etiqueta
        lblImgInicio2.setIcon(imagen);
        
        // Titulo de la ventana
        dialogPreguntasComunidades.setTitle("Preguntas de Comunidades");
        dialogPreguntasComunidades.setSize(700,307);
        dialogPreguntasComunidades.setLocationRelativeTo(null);
        dialogPreguntasComunidades.setVisible(true);
    }//GEN-LAST:event_bntAleatoriasComunidadToolActionPerformed

    private void btnAleatoriasProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatoriasProvinciasActionPerformed
        
        Controlador.randomProvincia(lblNumeroRandomProvincias);
        
        // Creamos una imagen
        ImageIcon imagen = new ImageIcon("img/mapaPuntos1.png");
        // Actualizamos la imagen
        imagen = new ImageIcon(imagen.getImage().getScaledInstance(350, 240, Image.SCALE_DEFAULT));
        // Colocamos la imagen en la etiqueta
        lblImgInicio1.setIcon(imagen);
        
        // Titulo de la ventana
        dialogPreguntasProvincias.setTitle("Preguntas de provincias");
        dialogPreguntasProvincias.setSize(700,307);
        dialogPreguntasProvincias.setLocationRelativeTo(null);
        dialogPreguntasProvincias.setVisible(true);
    }//GEN-LAST:event_btnAleatoriasProvinciasActionPerformed

    private void btnAleatoriasComunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatoriasComunidadActionPerformed
        // TODO add your handling code here:
        Controlador.randomComunidad(lblNumeroRandomComunidad);
        
        // Creamos una imagen
        ImageIcon imagen = new ImageIcon("img/mapaPuntos2.png");
        // Actualizamos la imagen
        imagen = new ImageIcon(imagen.getImage().getScaledInstance(350, 240, Image.SCALE_DEFAULT));
        // Colocamos la imagen en la etiqueta
        lblImgInicio2.setIcon(imagen);
        
        // Titulo de la ventana
        dialogPreguntasComunidades.setTitle("Preguntas de Comunidades");
        dialogPreguntasComunidades.setSize(700,307);
        dialogPreguntasComunidades.setLocationRelativeTo(null);
        dialogPreguntasComunidades.setVisible(true);
    }//GEN-LAST:event_btnAleatoriasComunidadActionPerformed

    private void bntAleatoriasProvinciasToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAleatoriasProvinciasToolActionPerformed
        // TODO add your handling code here:
        Controlador.randomProvincia(lblNumeroRandomProvincias);
        
        // Creamos una imagen
        ImageIcon imagen = new ImageIcon("img/mapaPuntos1.png");
        // Actualizamos la imagen
        imagen = new ImageIcon(imagen.getImage().getScaledInstance(350, 240, Image.SCALE_DEFAULT));
        // Colocamos la imagen en la etiqueta
        lblImgInicio1.setIcon(imagen);
        
        // Titulo de la ventana
        dialogPreguntasProvincias.setTitle("Preguntas de provincias");
        dialogPreguntasProvincias.setSize(700,307);
        dialogPreguntasProvincias.setLocationRelativeTo(null);
        dialogPreguntasProvincias.setVisible(true);
    }//GEN-LAST:event_bntAleatoriasProvinciasToolActionPerformed

    private void itemAleatoriasProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAleatoriasProvinciasActionPerformed
        // TODO add your handling code here:
        Controlador.randomProvincia(lblNumeroRandomProvincias);
        
        // Creamos una imagen
        ImageIcon imagen = new ImageIcon("img/mapaPuntos1.png");
        // Actualizamos la imagen
        imagen = new ImageIcon(imagen.getImage().getScaledInstance(350, 240, Image.SCALE_DEFAULT));
        // Colocamos la imagen en la etiqueta
        lblImgInicio1.setIcon(imagen);
        
        // Titulo de la ventana
        dialogPreguntasProvincias.setTitle("Preguntas de provincias");
        dialogPreguntasProvincias.setSize(700,307);
        dialogPreguntasProvincias.setLocationRelativeTo(null);
        dialogPreguntasProvincias.setVisible(true);
    }//GEN-LAST:event_itemAleatoriasProvinciasActionPerformed

    private void itemAleatoriasComunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAleatoriasComunidadActionPerformed
        // TODO add your handling code here:
        Controlador.randomComunidad(lblNumeroRandomComunidad);
        
        // Creamos una imagen
        ImageIcon imagen = new ImageIcon("img/mapaPuntos2.png");
        // Actualizamos la imagen
        imagen = new ImageIcon(imagen.getImage().getScaledInstance(350, 240, Image.SCALE_DEFAULT));
        // Colocamos la imagen en la etiqueta
        lblImgInicio2.setIcon(imagen);
        
        // Titulo de la ventana
        dialogPreguntasComunidades.setTitle("Preguntas de Comunidades");
        dialogPreguntasComunidades.setSize(700,307);
        dialogPreguntasComunidades.setLocationRelativeTo(null);
        dialogPreguntasComunidades.setVisible(true);        
    }//GEN-LAST:event_itemAleatoriasComunidadActionPerformed

    private void btnResponderProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderProvinciasActionPerformed
        // TODO add your handling code here:
        Controlador.preguntarProvincia(txtRespuestaProvincias, lblNumeroRandomProvincias, dialogPreguntasProvincias);
    }//GEN-LAST:event_btnResponderProvinciasActionPerformed

    private void btnRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuesta2ActionPerformed
        // TODO add your handling code here:
        Controlador.preguntarComunidad(txtResponderComunidad, lblNumeroRandomComunidad, dialogPreguntasComunidades);
    }//GEN-LAST:event_btnRespuesta2ActionPerformed

    private void btnCapitalProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapitalProvinciaActionPerformed
        // TODO add your handling code here:
        Controlador.randomNombreProvincia(lblCapitalesProvincias);
        
        // Titulo de la ventana
        dialogPreguntasCapitalProvincias.setTitle("Preguntando Capitales por provincias");
        dialogPreguntasCapitalProvincias.setSize(370,305);
        dialogPreguntasCapitalProvincias.setLocationRelativeTo(null);
        dialogPreguntasCapitalProvincias.setVisible(true); 
    }//GEN-LAST:event_btnCapitalProvinciaActionPerformed

    private void btnResponderCapitalesProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderCapitalesProvinciasActionPerformed
        // TODO add your handling code here:
        Controlador.preguntarCapital(txtRespuestaCapitalesProvincias, lblCapitalesProvincias, dialogPreguntasCapitalProvincias);
    }//GEN-LAST:event_btnResponderCapitalesProvinciasActionPerformed

    private void btnResponderProvinciasCapitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderProvinciasCapitalesActionPerformed
        // TODO add your handling code here:
        Controlador.preguntarNomProvincia(txtRespuestaProvinciasCapitales, lblNombreCapital, dialogPreguntasProvinciasCapital);
    }//GEN-LAST:event_btnResponderProvinciasCapitalesActionPerformed

    private void btnProvinciaCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvinciaCapitalActionPerformed
        // TODO add your handling code here:
        Controlador.randomNombreCapital(lblNombreCapital);
        
        // Titulo de la ventana
        dialogPreguntasProvinciasCapital.setTitle("Preguntando Provincias por Capitales");
        dialogPreguntasProvinciasCapital.setSize(370,305);
        dialogPreguntasProvinciasCapital.setLocationRelativeTo(null);
        dialogPreguntasProvinciasCapital.setVisible(true);
    }//GEN-LAST:event_btnProvinciaCapitalActionPerformed

    private void btnCapitalProvinciaToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapitalProvinciaToolActionPerformed
        // TODO add your handling code here:
        Controlador.randomNombreProvincia(lblCapitalesProvincias);
        
        // Titulo de la ventana
        dialogPreguntasCapitalProvincias.setTitle("Preguntando Capitales por provincias");
        dialogPreguntasCapitalProvincias.setSize(370,305);
        dialogPreguntasCapitalProvincias.setLocationRelativeTo(null);
        dialogPreguntasCapitalProvincias.setVisible(true);
    }//GEN-LAST:event_btnCapitalProvinciaToolActionPerformed

    private void btnProvinciaCapitalToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvinciaCapitalToolActionPerformed
        // TODO add your handling code here:
        Controlador.randomNombreCapital(lblNombreCapital);
        
        // Titulo de la ventana
        dialogPreguntasProvinciasCapital.setTitle("Preguntando Provincias por Capitales");
        dialogPreguntasProvinciasCapital.setSize(370,305);
        dialogPreguntasProvinciasCapital.setLocationRelativeTo(null);
        dialogPreguntasProvinciasCapital.setVisible(true);
    }//GEN-LAST:event_btnProvinciaCapitalToolActionPerformed

    private void itemCapitalProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCapitalProvinciaActionPerformed
        // TODO add your handling code here:
        Controlador.randomNombreProvincia(lblCapitalesProvincias);
        
        // Titulo de la ventana
        dialogPreguntasCapitalProvincias.setTitle("Preguntando Capitales por provincias");
        dialogPreguntasCapitalProvincias.setSize(370,305);
        dialogPreguntasCapitalProvincias.setLocationRelativeTo(null);
        dialogPreguntasCapitalProvincias.setVisible(true);
    }//GEN-LAST:event_itemCapitalProvinciaActionPerformed

    private void itemProvinciaCaptialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProvinciaCaptialActionPerformed
        // TODO add your handling code here:
        Controlador.randomNombreCapital(lblNombreCapital);
        
        // Titulo de la ventana
        dialogPreguntasProvinciasCapital.setTitle("Preguntando Provincias por Capitales");
        dialogPreguntasProvinciasCapital.setSize(370,305);
        dialogPreguntasProvinciasCapital.setLocationRelativeTo(null);
        dialogPreguntasProvinciasCapital.setVisible(true);
    }//GEN-LAST:event_itemProvinciaCaptialActionPerformed

    private void itemInfoProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInfoProvinciaActionPerformed
        // TODO add your handling code here:
        dialogInforProvincias.setTitle("Informacion");
        
        // Titulo de la ventana
        dialogInforProvincias.setSize(430,350);
        dialogInforProvincias.setLocationRelativeTo(null);
        dialogInforProvincias.setVisible(true);
    }//GEN-LAST:event_itemInfoProvinciaActionPerformed

    private void menuSobreMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreMiActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Diseñado por Ruben Palomo Yuste. \nEstudiante de 2º de DAM");
    }//GEN-LAST:event_menuSobreMiActionPerformed

    private void menuSobreMi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreMi2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Diseñado por Ruben Palomo Yuste. \nEstudiante de 2º de DAM");
    }//GEN-LAST:event_menuSobreMi2ActionPerformed

    private void menuSobreMi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreMi1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Diseñado por Ruben Palomo Yuste. \nEstudiante de 2º de DAM");
    }//GEN-LAST:event_menuSobreMi1ActionPerformed

    private void menuSobreMi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreMi3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Diseñado por Ruben Palomo Yuste. \nEstudiante de 2º de DAM");
    }//GEN-LAST:event_menuSobreMi3ActionPerformed

    private void menuSobreMi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreMi4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Diseñado por Ruben Palomo Yuste. \nEstudiante de 2º de DAM");
    }//GEN-LAST:event_menuSobreMi4ActionPerformed

    private void itemInfoProvincia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInfoProvincia4ActionPerformed
        // TODO add your handling code here:
        
        // Titulo de la ventana
        dialogInforProvincias.setTitle("Informacion");
        dialogInforProvincias.setSize(430,350);
        dialogInforProvincias.setLocationRelativeTo(null);
        dialogInforProvincias.setVisible(true);
    }//GEN-LAST:event_itemInfoProvincia4ActionPerformed

    private void itemInfoProvincia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInfoProvincia3ActionPerformed
        // TODO add your handling code here:
        
        // Titulo de la ventana
        dialogInforProvincias.setTitle("Informacion");
        dialogInforProvincias.setSize(430,350);
        dialogInforProvincias.setLocationRelativeTo(null);
        dialogInforProvincias.setVisible(true);
    }//GEN-LAST:event_itemInfoProvincia3ActionPerformed

    private void itemInfoProvincia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInfoProvincia2ActionPerformed
        // TODO add your handling code here:
        
        // Titulo de la ventana
        dialogInforProvincias.setTitle("Informacion");
        dialogInforProvincias.setSize(430,350);
        dialogInforProvincias.setLocationRelativeTo(null);
        dialogInforProvincias.setVisible(true);
    }//GEN-LAST:event_itemInfoProvincia2ActionPerformed

    private void itemInfoProvincia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInfoProvincia1ActionPerformed
        // TODO add your handling code here:
        
        // Titulo de la ventana
        dialogInforProvincias.setTitle("Informacion");
        dialogInforProvincias.setSize(430,350);
        dialogInforProvincias.setLocationRelativeTo(null);
        dialogInforProvincias.setVisible(true);
    }//GEN-LAST:event_itemInfoProvincia1ActionPerformed

    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed
        // TODO add your handling code here:
        
        // Titulo de la ventana
        dialogAyuda.setTitle("Ayuda");
        dialogAyuda.setSize(450,320);
        dialogAyuda.setLocationRelativeTo(null);
        dialogAyuda.setVisible(true);
    }//GEN-LAST:event_menuInfoActionPerformed

    private void menuInfo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfo4ActionPerformed
        // TODO add your handling code here:
        
        // Titulo de la ventana
        dialogAyuda.setTitle("Ayuda");
        dialogAyuda.setSize(450,320);
        dialogAyuda.setLocationRelativeTo(null);
        dialogAyuda.setVisible(true);
    }//GEN-LAST:event_menuInfo4ActionPerformed

    private void menuInfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfo2ActionPerformed
        // TODO add your handling code here:
        
        // Titulo de la ventana
        dialogAyuda.setTitle("Ayuda");
        dialogAyuda.setSize(450,320);
        dialogAyuda.setLocationRelativeTo(null);
        dialogAyuda.setVisible(true);
    }//GEN-LAST:event_menuInfo2ActionPerformed

    private void menuInfo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfo3ActionPerformed
        // TODO add your handling code here:
        
        // Titulo de la ventana
        dialogAyuda.setTitle("Ayuda");
        dialogAyuda.setSize(450,320);
        dialogAyuda.setLocationRelativeTo(null);
        dialogAyuda.setVisible(true);
    }//GEN-LAST:event_menuInfo3ActionPerformed

    private void menuInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfo1ActionPerformed
        // TODO add your handling code here:
        
        // Titulo de la ventana
        dialogAyuda.setTitle("Ayuda");
        dialogAyuda.setSize(450,320);
        dialogAyuda.setLocationRelativeTo(null);
        dialogAyuda.setVisible(true);
    }//GEN-LAST:event_menuInfo1ActionPerformed

    private void btnCerrarAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarAyudaActionPerformed
        // TODO add your handling code here:
        dialogAyuda.dispose();
    }//GEN-LAST:event_btnCerrarAyudaActionPerformed

    private void btnCerrarInfoProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarInfoProvinciaActionPerformed
        // TODO add your handling code here:
        dialogInforProvincias.dispose();
    }//GEN-LAST:event_btnCerrarInfoProvinciaActionPerformed

    private void btnVerProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProvinciaActionPerformed
        // TODO add your handling code here:
        Controlador.informacionProvincia(txtProvincia, lblNombreProvincia, lblInfoProvincia, lblImg1Provincia, lblImg2Provincia, lblImg3Provincia);
    }//GEN-LAST:event_btnVerProvinciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAleatoriasComunidadTool;
    private javax.swing.JButton bntAleatoriasProvinciasTool;
    private javax.swing.JButton btnAleatoriasComunidad;
    private javax.swing.JButton btnAleatoriasProvincias;
    private javax.swing.JButton btnCapitalProvincia;
    private javax.swing.JButton btnCapitalProvinciaTool;
    private javax.swing.JButton btnCerrarAyuda;
    private javax.swing.JButton btnCerrarInfoProvincia;
    private javax.swing.JButton btnProvinciaCapital;
    private javax.swing.JButton btnProvinciaCapitalTool;
    private javax.swing.JButton btnResponderCapitalesProvincias;
    private javax.swing.JButton btnResponderProvincias;
    private javax.swing.JButton btnResponderProvinciasCapitales;
    private javax.swing.JButton btnRespuesta2;
    private javax.swing.JButton btnVerProvincia;
    private javax.swing.JDialog dialogAyuda;
    private javax.swing.JDialog dialogInforProvincias;
    private javax.swing.JDialog dialogPreguntasCapitalProvincias;
    private javax.swing.JDialog dialogPreguntasComunidades;
    private javax.swing.JDialog dialogPreguntasProvincias;
    private javax.swing.JDialog dialogPreguntasProvinciasCapital;
    private javax.swing.JMenuItem itemAleatoriasComunidad;
    private javax.swing.JMenuItem itemAleatoriasProvincias;
    private javax.swing.JMenuItem itemCapitalProvincia;
    private javax.swing.JMenuItem itemInfoProvincia;
    private javax.swing.JMenuItem itemInfoProvincia1;
    private javax.swing.JMenuItem itemInfoProvincia2;
    private javax.swing.JMenuItem itemInfoProvincia3;
    private javax.swing.JMenuItem itemInfoProvincia4;
    private javax.swing.JMenuItem itemProvinciaCaptial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCapitalesProvincias;
    private javax.swing.JLabel lblEnunciado;
    private javax.swing.JLabel lblEnunciado1;
    private javax.swing.JLabel lblEnunciado2;
    private javax.swing.JLabel lblEnunciado3;
    private javax.swing.JLabel lblEnunciado4;
    private javax.swing.JLabel lblEnunciado5;
    private javax.swing.JLabel lblEnunciado6;
    private javax.swing.JLabel lblImg1Provincia;
    private javax.swing.JLabel lblImg2Provincia;
    private javax.swing.JLabel lblImg3Provincia;
    private javax.swing.JLabel lblImgInicio;
    private javax.swing.JLabel lblImgInicio1;
    private javax.swing.JLabel lblImgInicio2;
    private javax.swing.JLabel lblInfoProvincia;
    private javax.swing.JLabel lblNombreCapital;
    private javax.swing.JLabel lblNombreProvincia;
    private javax.swing.JLabel lblNumeroRandomComunidad;
    private javax.swing.JLabel lblNumeroRandomProvincias;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuAyuda1;
    private javax.swing.JMenu menuAyuda2;
    private javax.swing.JMenu menuAyuda3;
    private javax.swing.JMenu menuAyuda4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuBar menuBar1;
    private javax.swing.JMenuBar menuBar2;
    private javax.swing.JMenuBar menuBar3;
    private javax.swing.JMenuBar menuBar4;
    private javax.swing.JMenuItem menuInfo;
    private javax.swing.JMenuItem menuInfo1;
    private javax.swing.JMenuItem menuInfo2;
    private javax.swing.JMenuItem menuInfo3;
    private javax.swing.JMenuItem menuInfo4;
    private javax.swing.JMenu menuInformacion;
    private javax.swing.JMenu menuInformacion1;
    private javax.swing.JMenu menuInformacion2;
    private javax.swing.JMenu menuInformacion3;
    private javax.swing.JMenu menuInformacion4;
    private javax.swing.JMenu menuPreguntar;
    private javax.swing.JMenuItem menuSobreMi;
    private javax.swing.JMenuItem menuSobreMi1;
    private javax.swing.JMenuItem menuSobreMi2;
    private javax.swing.JMenuItem menuSobreMi3;
    private javax.swing.JMenuItem menuSobreMi4;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtResponderComunidad;
    private javax.swing.JTextField txtRespuestaCapitalesProvincias;
    private javax.swing.JTextField txtRespuestaProvincias;
    private javax.swing.JTextField txtRespuestaProvinciasCapitales;
    // End of variables declaration//GEN-END:variables
}
